const allQuestions = [
    /* SCIENCE */
    {category:"Science",question:"What is the Symbol of Gold?",choices:["Au","Ag","Gd","Go"],answer:"Au"},
    {category:"Science",question:"What is called the Red Planet?",choices:["Mars","Earth","Jupiter","Saturn"],answer:"Mars"},
    {category:"Science",question:"It is a Powerhouse of cell?",choices:["Nucleus","Mitochondria","Ribosome","DNA"],answer:"Mitochondria"},
    {category:"Science",question:"What is the boiling point of water (Celsius)?",choices:["50","90","100","120"],answer:"100"},
    {category:"Science",question:"What is the hardest natural substance?",choices:["Iron","Diamond","Gold","Quartz"],answer:"Diamond"},
    {category:"Science",question:"What gas do plants absorb?",choices:["Oxygen","Carbon Dioxide","Nitrogen","Hydrogen"],answer:"Carbon Dioxide"},
    {category:"Science",question:"How many bones does an adult human have?",choices:["200","206","210","215"],answer:"206"},
    {category:"Science",question:"What is the speed of light approx?",choices:["300k km/s","100k","500k","1M"],answer:"300k km/s"},
    {category:"Science",question:"Who formulated the theory of relativity?",choices:["Newton","Einstein","Tesla","Galileo"],answer:"Einstein"},
    {category:"Science",question:"Most abundant gas in Earth's atmosphere?",choices:["Oxygen","Nitrogen","CO2","Helium"],answer:"Nitrogen"},
    /* HISTORY */
    {category:"History",question:"In what year did WWII end?",choices:["1940","1943","1945","1950"],answer:"1945"},
    {category:"History",question:"Who was the First US President?",choices:["Lincoln","Adams","Washington","Jefferson"],answer:"Washington"},
    {category:"History",question:"When did the Titanic sink?",choices:["1905","1912","1920","1930"],answer:"1912"},
    {category:"History",question:"Who were the Great Wall's main enemies?",choices:["Mongols","Romans","Persians","Japanese"],answer:"Mongols"},
    {category:"History",question:"Who was the first female UK PM?",choices:["May","Thatcher","Elizabeth","Merkel"],answer:"Thatcher"},
    {category:"History",question:"Who is credited with discovering America?",choices:["Columbus","Magellan","Cook","Drake"],answer:"Columbus"},
    {category:"History",question:"Julius Caesar led which empire?",choices:["Roman","Greek","Ottoman","British"],answer:"Roman"},
    {category:"History",question:"Who gave the 'I Have a Dream' speech?",choices:["Mandela","King","Malcolm X","Parks"],answer:"King"},
    {category:"History",question:"Ancient Egypt writing system?",choices:["Runes","Latin","Hieroglyphics","Cuneiform"],answer:"Hieroglyphics"},
    {category:"History",question:"The Cold War was a rivalry with whom?",choices:["China","Germany","Soviet Union","Japan"],answer:"Soviet Union"},
    /* POP CULTURE */
    {category:"Pop Culture",question:"Who played Jack in Titanic?",choices:["Pitt","Cruise","DiCaprio","Depp"],answer:"DiCaprio"},
    {category:"Pop Culture",question:"Highest grossing film of all time?",choices:["Avatar","Endgame","Titanic","Star Wars"],answer:"Avatar"},
    {category:"Pop Culture",question:"Who is the King of Pop?",choices:["Prince","Jackson","Elvis","Madonna"],answer:"Jackson"},
    {category:"Pop Culture",question:"What is Harry Potter's house?",choices:["Gryffindor","Slytherin","Ravenclaw","Hufflepuff"],answer:"Gryffindor"},
    {category:"Pop Culture",question:"What is the land in Game of Thrones?",choices:["Narnia","Westeros","Hogwarts","Middle Earth"],answer:"Westeros"},
    {category:"Pop Culture",question:"First American Idol winner?",choices:["Clarkson","Underwood","Hudson","Lambert"],answer:"Clarkson"},
    {category:"Pop Culture",question:"Who is the Caped Crusader?",choices:["Batman","Superman","Ironman","Spiderman"],answer:"Batman"},
    {category:"Pop Culture",question:"Most popular block building game?",choices:["Roblox","Minecraft","Fortnite","Terraria"],answer:"Minecraft"},
    {category:"Pop Culture",question:"Who is the main ogre in the movie Shrek?",choices:["Shrek","Donkey","Fiona","Farquaad"],answer:"Shrek"},
    {category:"Pop Culture",question:"What kind of animal is Mickey’s dog Pluto?",choices:["Goofy","Donald","Dog","Snoopy"],answer:"Dog"}
];
